/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.continuada;

/**
 *
 * @author Pichau
 */
public class Tela1 extends javax.swing.JFrame {

    /**
     * Creates new form Tela1
     */
    public Tela1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Barra3 = new javax.swing.JProgressBar();
        Barra1 = new javax.swing.JProgressBar();
        Barra2 = new javax.swing.JProgressBar();
        lbMemoria = new javax.swing.JLabel();
        lbCPU = new javax.swing.JLabel();
        lbDisc = new javax.swing.JLabel();
        btLeitura = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(214, 168, 247));
        getContentPane().setLayout(null);
        getContentPane().add(Barra3);
        Barra3.setBounds(60, 280, 530, 30);
        getContentPane().add(Barra1);
        Barra1.setBounds(60, 100, 530, 30);
        getContentPane().add(Barra2);
        Barra2.setBounds(60, 190, 530, 30);

        lbMemoria.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        lbMemoria.setText("MEMORIA");
        getContentPane().add(lbMemoria);
        lbMemoria.setBounds(60, 250, 90, 30);

        lbCPU.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        lbCPU.setText("CPU");
        getContentPane().add(lbCPU);
        lbCPU.setBounds(60, 70, 80, 30);

        lbDisc.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        lbDisc.setText("DISCO");
        getContentPane().add(lbDisc);
        lbDisc.setBounds(60, 160, 80, 30);

        btLeitura.setText("Leitura de dados");
        getContentPane().add(btLeitura);
        btLeitura.setBounds(210, 350, 200, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Gerador de dados");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 0, 210, 50);

        setSize(new java.awt.Dimension(663, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Barra1;
    private javax.swing.JProgressBar Barra2;
    private javax.swing.JProgressBar Barra3;
    private javax.swing.JButton btLeitura;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbCPU;
    private javax.swing.JLabel lbDisc;
    private javax.swing.JLabel lbMemoria;
    // End of variables declaration//GEN-END:variables
}
