/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.continuada;

import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author Pichau
 */
public class Tela1 extends javax.swing.JFrame {

    /**
     * Creates new form Tela1
     */
    public Tela1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        prgbBarra3 = new javax.swing.JProgressBar();
        prgbBarra2 = new javax.swing.JProgressBar();
        prgbBarra1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAcao = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        jLabel1.setText("Memoria");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 270, 80, 25);

        prgbBarra3.setMaximum(80);
        getContentPane().add(prgbBarra3);
        prgbBarra3.setBounds(80, 300, 530, 40);
        getContentPane().add(prgbBarra2);
        prgbBarra2.setBounds(80, 210, 530, 40);

        prgbBarra1.setMaximum(40);
        getContentPane().add(prgbBarra1);
        prgbBarra1.setBounds(80, 120, 530, 40);

        jLabel2.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 36)); // NOI18N
        jLabel2.setText("Gerador de dados");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 0, 270, 70);

        jLabel4.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        jLabel4.setText("Disco");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 180, 60, 25);

        jLabel5.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        jLabel5.setText("CPU");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 90, 60, 25);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        btnAcao.setText("Gerar dados");
        btnAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcaoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAcao);
        btnAcao.setBounds(270, 360, 130, 30);

        jLabel6.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jLabel6.setText("max (4 GHz)");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(510, 100, 110, 19);

        jLabel3.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jLabel3.setText("max (8 GB)");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(520, 280, 90, 19);

        jLabel7.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jLabel7.setText("max (100%)");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(520, 190, 90, 19);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 690, 400);

        setSize(new java.awt.Dimension(703, 441));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcaoActionPerformed
        // TODO add your handling code here:
        Double sorteio1 = ThreadLocalRandom.current().nextDouble(0, 4);
        Integer sorteio2 = ThreadLocalRandom.current().nextInt(0, 100);
        Double sorteio3 = ThreadLocalRandom.current().nextDouble(0, 8);
        Double result1 = sorteio1 * 10;
        Double result3 = sorteio3 * 10;
        prgbBarra1.setStringPainted(true);
        prgbBarra2.setStringPainted(true);
        prgbBarra3.setStringPainted(true);
        prgbBarra1.setValue(result1.intValue());
        prgbBarra2.setValue(sorteio2);
        prgbBarra3.setValue(result3.intValue());
        
    }//GEN-LAST:event_btnAcaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar prgbBarra1;
    private javax.swing.JProgressBar prgbBarra2;
    private javax.swing.JProgressBar prgbBarra3;
    // End of variables declaration//GEN-END:variables
}
